# Generated by Django 5.2.6 on 2026-03-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_likes', to='accounts.account', verbose_name='Аккаунт')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'constraints': [models.UniqueConstraint(fields=('account', 'post'), name='unique Like')],
            },
        ),
    ]
