# Generated by Django 5.2.6 on 2026-03-11 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique Like',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('account', 'post')},
        ),
    ]
